### ISSUE TITLE
Disable Privacy Policy update announcement banner

### ISSUE THREAD

**Issue by ryangoree** [delvtech/council-kit#427]
A banner is being added to the landing page in #426 to notify users that we've updated our privacy policy (related to https://github.com/delvtech/hyperdrive-frontend/issues/886). This banner needs to be active for 2 weeks after rolling out the new privacy policy which will be today (May 20, 2024). Meaning the banner should be disabled on **June 04, 2024**.

**Comment by akhamisa** [comment]
@ryangoree let's please go ahead and disable the banner. Thanks!
